insert into vehicle (plate, model, manufacturer, color, status )
values 
('AAA-1234', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('BBB-1235', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('CCC-1236', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('DDD-1237', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('EEE-1238', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('FFF-1239', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('GGG-1234', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('HHH-1235', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('III-1236', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('JJJ-1237', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('KKK-1238', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('LLL-1239', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('MMM-1234', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('NNN-1235', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('OOO-1236', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('PPP-1237', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('QQQ-1238', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('RRR-1239', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('SSS-1234', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('TTT-1234', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('UUU-1234', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('VVV-1234', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('XXX-1234', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('YYY-1234', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('WWW-1234', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true),
('ZZZ-1234', 'Class C 1.6 Advantgarde Turbo Flex', 'Mercedes-Benz', 'Black', true);

select sysdate;